on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: echo  The tag is [${{ github.event.inputs.environment }}] and the secret is [$TEST_SECRET] 
